export {default as Premier } from './Premier'
export {default as LiveEvent} from './LiveEvent'
export {default as RecomandedMovie} from './RecomandedMovie'
export {default as Slider} from './Slider'
export {default as Tabbar} from './Tabbar'
export {default as Navbar} from './Navbar'